SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,M.FIRST_NAME MGR_FIRST,M.LAST_NAME MGR_LAST,M.EMPLOYEE_ID MGR_ID,
D.DEPARTMENT_NAME,L.CITY,C.COUNTRY_NAME
FROM HR.EMPLOYEES E LEFT JOIN HR.EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID 
FULL JOIN HR.DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
FULL JOIN HR.LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
FULL JOIN HR.COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID
ORDER BY E.EMPLOYEE_ID;