SELECT * FROM SCOTT.EMP;


-- FOR EACH EMPLOYEE,LIST THEIR EMPNO AND NAME OF MANAGER ALONG WITH MANAGER EMPNO
-- SKIP LEVEL IS MANAGER OF MANAGER
SELECT A.EMPNO,A.ENAME,B.ENAME MANAGER_NAME,B.EMPNO MANAGER_ID FROM SCOTT.EMP A LEFT JOIN SCOTT.EMP B 
ON A.MGR = B.EMPNO ORDER BY A.EMPNO;

-- FOR EACH EMPLOYEE,LIST THEIR EMPNO AND NAME OF MANAGER ALONG WITH MANAGER EMPNO,SKIP LEVEL MNG NO,SKIP LEVER MANAGER ID
-- SKIP LEVEL IS MANAGER OF MANAGER
SELECT D.EMPNO,D.ENAME,D.MANAGER_NAME,D.MANAGER_ID,C.ENAME SKIP_MGR,D.SKIP_MGR_ID FROM SCOTT.EMP C RIGHT JOIN (SELECT A.EMPNO,A.ENAME,B.ENAME MANAGER_NAME,B.EMPNO MANAGER_ID,B.MGR SKIP_MGR_ID FROM SCOTT.EMP A LEFT JOIN SCOTT.EMP B 
ON A.MGR = B.EMPNO ORDER BY A.EMPNO) D
ON D.SKIP_MGR_ID = C.EMPNO ORDER BY D.EMPNO;