-- NO OF EMPLOYEES GROUPED AND ORDERED BY DEPT NO IN DESCENDING ORDER
SELECT DEPTNO,COUNT(DEPTNO) FROM SCOTT.EMP GROUP BY DEPTNO ORDER BY DEPTNO DESC;

-- FIND DEPT WITH MAX EMPLOYEES
SELECT DEPTNO,COUNT(DEPTNO) FROM SCOTT.EMP GROUP BY DEPTNO ORDER BY DEPTNO DESC FETCH FIRST 1 ROW ONLY;

-- FIND DEPT WITH MAX SALARY EXPENSE
SELECT DEPTNO,SUM(SAL) EXPENSE FROM SCOTT.EMP GROUP BY DEPTNO ORDER BY EXPENSE DESC FETCH FIRST 1 ROW ONLY;

-- SELECT MAX & MIN SALARY FOR EACH DEPARTMENT
SELECT DEPTNO,MAX(SAL),MIN(SAL) FROM SCOTT.EMP GROUP BY DEPTNO ORDER BY DEPTNO;