-- SELECT ALL FROM DEPARTMENT
SELECT * FROM SCOTT.DEPT;

-- TRADITIONAL JOIN EXAMPLE
SELECT EMPNO,ENAME,E.DEPTNO,DNAME FROM SCOTT.EMP E,SCOTT.DEPT D WHERE E.DEPTNO = D.DEPTNO;

-- STANDARD JOIN EXAMPLE, (INNER JOIN == JOIN)
SELECT EMPNO,ENAME,E.DEPTNO,DNAME FROM SCOTT.EMP E INNER JOIN SCOTT.DEPT D ON E.DEPTNO = D.DEPTNO;

-- GET ALL DEPARTMENTS,EVEN ONE WITH NO EMPLOYEES, SO RIGHT OUTER JOIN
SELECT EMPNO,ENAME,D.DEPTNO,DNAME FROM SCOTT.EMP E RIGHT OUTER JOIN SCOTT.DEPT D ON E.DEPTNO = D.DEPTNO;

-- FULL OUTER JOIN
SELECT EMPNO,ENAME,D.DEPTNO,DNAME FROM SCOTT.EMP E FULL OUTER JOIN SCOTT.DEPT D ON E.DEPTNO = D.DEPTNO;