-- SELECT TOTAL RECORDS FROM EMP
SELECT COUNT(*) FROM SCOTT.EMP;

-- SELECT AVGERAGE SALARY OF ALL EMPLOYEES
SELECT ROUND(AVG(SAL)) FROM SCOTT.EMP;

-- SELECT ALL EMPS WHO SAL IS GREATER THAN OR EQUAL TO AVG SALARY
-- NON-CORELATED SUB QUERY AS INNER QUERY DOEN NOT REFERRING TO ANY COLUMN OF OUTER QUERY
SELECT * FROM SCOTT.EMP WHERE SAL >= (SELECT ROUND(AVG(SAL)) FROM SCOTT.EMP);

-- SELECT AVG SAL OF EMPLOYEES FROM RESPECTIVE DEPARTMENTS
SELECT DEPTNO,ROUND(AVG(SAL)) FROM SCOTT.EMP GROUP BY DEPTNO ORDER BY DEPTNO;


-- SELECT ALL EMPS WHO SAL IS GREATER THAN OR EQUAL TO AVG SALARY IN THEIR RESPECTIVE DEPARTMENTS
-- CORELATED SUB QUERY AS INNER QUERY IS REFERRING TO THE COLUMN OF OUTER QUERY
SELECT * FROM SCOTT.EMP OUTER WHERE SAL > (SELECT ROUND(AVG(SAL))FROM SCOTT.EMP INNER WHERE INNER.DEPTNO = OUTER.DEPTNO) ORDER BY DEPTNO;